### ISSUE TITLE
Are there any examples showing how to  use react-dwolla-iav in a react-native project?

### ISSUE THREAD

**Issue by DayZeroLLC** [jane/react-dwolla-iav#16]
Are there any example projects demonstrating how to use react-dwolla-iav in a react-native project? I guess it's clear to everyone else, but I'm lost on how to wire up outside the code fragment in the readme.  Any help pointing me to an example project is greatly appreciated.

**Comment by zacanger** [comment]
We don't have any React Native apps so we haven't tried that out, but since the IAV flow depends on being on web, I think you'd have to use a webview pointing to a url serving over https. That's a restriction on Dwolla's end from what I can see from their docs. Here are two links from their support forum that might be helpful:

* <https://discuss.dwolla.com/t/iav-react-native-and-dwolla/2204/2>
* <https://discuss.dwolla.com/t/error-with-iav-example-flow/2137/36>

**Comment by DayZeroLLC** [comment]
Thanks @zacanger
